# configurando o deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-nginx
  # configurando o pod que sera criado pelo deployment
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80

          # montando volume com o configmap no container
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf-volume
              readOnly: true

      # criando volume utilizando o arquivo configmap de configuracao do nginx
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
