apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec: # spec do deployment
  replicas: 1

  selector:
    matchLabels:
      app: mysql-server
      tier: db

  template: # referente ao POD
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec: # spec do POD
      containers:
        - image: mysql:5.7
          name: mysql-server
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
